version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: job_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: jobs
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: job_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5500:5500"
    volumes:
      - ./frontend:/app

  notifier:
    build:
      context: ./notifier
      dockerfile: Dockerfile
    container_name: job_notifier
    restart: always
    ports:
      - "8500:8500"
    environment:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    volumes:
      - ./notifier:/app

  health-checker:
    image: python:3.10
    container_name: job_health_checker
    restart: always
    depends_on:
      - backend
      - notifier
    volumes:
      - ./health-checker:/app
    working_dir: /app
    command: ["python", "check_health.py"]

volumes:
  mysql_data:
